# Generated by Django 5.2.3 on 2025-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_restaurant_owner_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
