# Generated by Django 5.2.3 on 2025-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_loginattempt_permission_alter_order_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('owner', 'Owner'), ('manager', 'Manager'), ('kitchen', 'Kitchen Staff'), ('staff', 'Restaurant Staff'), ('waiter', 'Waiter'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
